feat: execute command
Enapter/enapter-cli pull request #15
Opened 2023-02-15 10:56 UTC by danya

2023-02-16 02:53 UTC, kulti requested changes

2023-02-16 02:53 UTC, kulti commented on internal/app/enaptercli/cmd_devices_logs.go
> +	DeviceID string `json:"hardware_id"` // FIXME: Cloud API argument name
А чего ты тут пофиксишь? Это не относится к этому проекту, думаю, это бессмысленный комментарий.

Вы обсуждали, как протокол должен измениться? Может, проще не откладывать и уже сейчас в рубишной части научится device_id принимать, и тут сразу правильно написать? (скорее всего, эти правки в руби ты и сам можешь попробовать сделать)

2023-02-16 02:53 UTC, kulti commented on internal/app/enaptercli/testdata/device_upload_logs/simple/output
> +[#5] 2020-12-17T13:32:57Z [INFO] Started uploading blueprint[id=42cc8af1-cc60-4eeb-972f-0c0bfa6e3df5] on device[device_id=SIM-WTM]
Думаю, логичнее было бы теперь писать `device[id=...]`. Я так понял, что это эмуляция ответа от клауда. А что он теперь пишет? Если `device_id=...`, то ок, если нет, то предлагаю поправить, чтобы ближе к правде быть.

И SIM-WTM — это не device_id, если быть точным. Это hardware_id, а device_id чаще выглядит, как uuid. Опять же это лишь вопрос похожести тестов на реальность.

2023-02-16 02:53 UTC, kulti commented on internal/app/enaptercli/cmd_devices_execute_test.go
> +		testDeviceExecute(t, basePath, false, http.StatusForbidden)
false, true, false — это нечитаемо. Флаги-аргументы почти всегда кака. Как вариант, можно добавить опциональный параметр `extra_args`:
```
func testDeviceExecute(
	t *testing.T, basePath string, statusCode int, extra_ags ...string,
) {
```

2023-02-16 02:53 UTC, kulti commented on internal/app/enaptercli/cmd_devices_execute_test.go
> +func checkTestAppOutput(t *testing.T, basePath string, args []string) {
Если этот метод специфичный для тестов команд, то надо его переименовать. Если же он общий для всех, то надо другие тесты отрефакторить (лучше сначала отрефакторить, а потом в этих тестах использовать — понятнее история коммитов будет).

2023-02-17 18:40 UTC, danya commented on internal/app/enaptercli/cmd_devices_logs.go
> +	DeviceID string `json:"hardware_id"` // FIXME: Cloud API argument name
Точно-точно. Помечал эти места для себя (есть еще пара таких «пасхальных яиц») — забыл убрать перед коммитом.

Обсуждали, Никита обещал сделать два варианта, попробую сам.

2023-03-01 10:26 UTC, danya commented on internal/app/enaptercli/testdata/device_upload_logs/simple/output
> +[#5] 2020-12-17T13:32:57Z [INFO] Started uploading blueprint[id=42cc8af1-cc60-4eeb-972f-0c0bfa6e3df5] on device[device_id=SIM-WTM]
Обсудили, решили оставить старый интерфейс для старых команд и добавить поддержку `hardware_id ` для `devices execute`.

2023-03-01 10:27 UTC, danya commented on internal/app/enaptercli/cmd_devices_logs.go
> +	DeviceID string `json:"hardware_id"` // FIXME: Cloud API argument name
Обсудили, https://github.com/Enapter/enapter-cli/pull/15#discussion_r1121481694.

2023-03-01 10:33 UTC, danya commented on internal/app/enaptercli/cmd_devices_execute_test.go
> +func checkTestAppOutput(t *testing.T, basePath string, args []string) {
Скорее аналогичный код в других тестах слишком специфичный. Пока не придумал, как это можно было бы отрефакторить хорошо, поэтому переименовал.

2023-03-31 14:53 UTC, kulti approved these changes
Поверхностно посмотрел, что обсуждали ранее. Думаю, можно мержить.

2023-04-06 18:13 UTC, merged